3.1 Кнопка
js-tasks-ru/htmlcss-20220120_kato-balakina pull request #3
Opened 2022-01-31 17:31 UTC by ketewan

2022-01-31 17:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-31 17:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-01-31 21:34 UTC, GSemikozov requested changes

2022-01-31 21:34 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-weight: 500;
не хватает паддингов и font-family)

2022-02-05 20:49 UTC, ketewan commented on 03-lection1/01-button/button.css
> +    font-weight: 500;
1) font-family и так приезжает с *, в замечании имеется в виду, что * стоит заменить на html?
2) с паддингами тоже не очень понятно, на макетах нет примеров слишком длинного текста и того, какое поведение должно быть при этом. В файле reset я сбрасываю паддинг в 0 у кнопки, но я бы для кнопки тогда сделала как-то так: 
`   padding: 0 16px;
    text-overflow: ellipsis;
    overflow: hidden;
    white-space: nowrap;`
Насколько такое решение подойдет?

2022-02-05 20:50 UTC, ketewan commented on 03-lection1/01-button/button.css
> +    font-weight: 500;
Или не стоило задавать фиксированную ширину для кнопки?

2022-02-05 21:00 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-05 21:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-07 21:18 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-weight: 500;
1. тут такая история что - а если встроим кнопку в другой компонент у которого будет другой font-family? тогда приедет не совсем то что надо) Робота можно оставить как стандартный, то лучше задавать на body - тогда не будет проблемы с переопределением во внутренних компонентах
2. в кнопке не стоит фиксировать ширину, пусть длинный текст тянет ширину самостоятельно. Единственное - вполне оправданно для кнопки задать white-space: nowrap; + можно text-overflow: ellipsis; overflow: hidden; но только в том случае если мы все-таки зададим какой-нибудь max-width

2022-02-13 22:16 UTC, GSemikozov approved these changes

2022-02-13 22:16 UTC, merged